display:
  cycle: true
  inverted: false
  orientation: 90
  trendingmode: true
  showvolume: true
  showrank: true
  24h: true
  showip: true
  disptype: 3in7
  layout: 4
ticker:
  currency2: bitcoin
  currency3: bitcoin,ethereum,dogecoin,shiba-inu,litecoin,cardano,gala,pancakeswap
  currency: bitcoin,shiba-inu,ethereum,terra-luna,gala,dogecoin,cardano,litecoin
  exchange: default
  fiatcurrency2: usd,eur,gbp
  fiatcurrency: usd,usd,usd,usd,usd,usd
  sparklinedays: 1 
  updatefrequency: 300

